workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 60
    environment:
      vars:
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx3g"
    scripts:
      - name: Make gradlew executable (safe even if already)
        script: chmod +x ./gradlew || true
      - name: Build debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - app/build/outputs/apk/**/*.apk
